site_name: LATAM DOC
nav:
    - Home: index.md
    - Maestros:
        - Configuración: LATAM-Setup/LATAM-Setup.md
        - Letra de clase de comprobante: Maestros/LATAM-VoucherClassLetter.md
        - Tipo de clase de comprobante: Maestros/LATAM-VoucherClassType.md
        - Clase de comprobante: Maestros/LATAM-VoucherClass.md
        - Punto de ventas: Maestros/LATAM-SalesPoint.md
        - Tipo documento: Maestros/LATAM-DocumentType.md
        - Tipo contribuyente: Maestros/LATAM-TaxPayerType.md
        - Grupo tipo de cuenta: Maestros/LATAM-AccountTypeGroup.md
        - Estado: Maestros/LATAM-State.md
    - Extensiones:
        - Exntesión de documento: LATAM-DocumentExtension.md
        - Compañía: Extensiones/LATAM-CompanyInformation.md
        - Cliente: Extensiones/LATAM-Customer.md
        - Proveedor: Extensiones/LATAM-Vendor.md
        - Banco: Extensiones/LATAM-Bank.md
        - Ordenes de ventas: Extensiones/LATAM-SalesOrder.md
        - Paises/Regiones: Extensiones/LATAM-CountriesRegion.md
    - Desarrollo:
        - Code Units:
            - LATAM SalesHeaderDocExt: Desarrollo/Code-Units/LATAM-SalesHeaderDocExt.md
            - LATAM Document Extension: Desarrollo/Code-Units/LATAM-Document-Extension.md
            - LATAM Sales Post Subscribers: Desarrollo/Code-Units/LATAM-SalesPostSubscribers.md
            - LATAM Purchase Post Subscribers: Desarrollo/Code-Units/LATAM-PurchasePostSubscribers.md
        - Enums:
            - LATAM Document Extension Type: Desarrollo/Enums/LATAM-DocumentExtensionType.md
            - LATAM Entity Type: Desarrollo/Enums/LATAM-EntityType/LATAM-EntityType.md
        - Queries: 
            - LATAM Voucher Class Lookup: Desarrollo/Queries/LATAM-VoucherClassLookup/LATAM-VoucherClassLookup.md
    - Info Extra:
        - Máscara Documentos: Info-Extra/Mascara.md
    - Acerca de: about.md
theme: readthedocs